name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish Sledge.Formats
      uses: brandedoutcast/publish-nuget@v2
      with:
          PROJECT_FILE_PATH: Sledge.Formats/Sledge.Formats.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish Sledge.Formats.Bsp
      uses: brandedoutcast/publish-nuget@v2
      with:
          PROJECT_FILE_PATH: Sledge.Formats.Bsp/Sledge.Formats.Bsp.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish Sledge.Formats.Map
      uses: brandedoutcast/publish-nuget@v2
      with:
          PROJECT_FILE_PATH: Sledge.Formats.Map/Sledge.Formats.Map.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish Sledge.Formats.Texture
      uses: brandedoutcast/publish-nuget@v2
      with:
          PROJECT_FILE_PATH: Sledge.Formats.Texture/Sledge.Formats.Texture.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish Sledge.Formats.Packages
      uses: brandedoutcast/publish-nuget@v2
      with:
          PROJECT_FILE_PATH: Sledge.Formats.Packages/Sledge.Formats.Packages.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish Sledge.Formats.GameData
      uses: brandedoutcast/publish-nuget@v2
      with:
          PROJECT_FILE_PATH: Sledge.Formats.GameData/Sledge.Formats.GameData.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
